name: ml4me-student
channels:
  - conda-forge
dependencies:
  - python=3.11.8
  - pip
  - pip:
      - geomloss>=0.2.6
  
  # CUDA and cuDNN for GPU support
  - conda-forge::cuda=12.8
  - conda-forge::cudnn
